### PR TITLE
Add Link to Rails-Sql.org

### PR DESCRIPTION
**Pull request by tradesmanhelix**

### CODE REVIEW

**Comment by tradesmanhelix** [comment]
Hi @stockandawe. Apologies - I pushed the blog post for last Friday's security update on Friday during the on-site. However, looks like I accidentally pushed straight to master but that didn't kick off the deploy, so I'm creating a PR with a small change that should kick off a deploy.

I've got a better system in place on my side so that this doesn't happen again and the posts won't go straight to master without first going through PR. Thank you!

**Comment by stockandawe** [comment]
@tradesmanhelix , ah I see. Looks like your PR went to the original repo where we forked this jekyll repo from. 
I don't see the full post in your PR -- only the last change as a commit. That might not work, right?

**Comment by tradesmanhelix** [comment]
> @tradesmanhelix , ah I see. Looks like your PR went to the original repo where we forked this jekyll repo from. I don't see the full post in your PR -- only the last change as a commit. That might not work, right?

@stockandawe - actually, the post is already in our master: https://github.com/himaxwell/himaxwell.github.io/blob/master/_posts/2022-04-30-security-debrief.md

I pushed from my CLI to master by accident (I thought I was on a branch but wasn't). And then yes my original PR was to the forked repo, but that PR is closed out and this is the one that we should merge. I think it should make a small change + kick off a build?

**Comment by stockandawe** [comment]
@tradesmanhelix , ah I see. My mistake, I thought this was for a new post.

**Review by stockandawe — APPROVED** [review]
👍

**Comment by tradesmanhelix** [comment]
@stockandawe - thank you and sorry for the confusion! I'll be sure to get this ironed out for this week's post! 😄

**Pull request merged**
